version: '2'
services:
  system:
    container_name: system-cuac-container
    build: .
    ports:
      - "4567:4567"
    volumes:
     - .:/opt/app/culturaaccesible-system
     - bundle:/usr/local/bundle

    links:
      - selenium
      - mongo
    command: bash -c "sh ensure_vendorization.sh"

  selenium:
    container_name: chrome-cuac-container
    image: selenium/standalone-chrome
    ports:
        - "4444:4444"
    logging:
      driver: none

  mongo:
    container_name: mongo-cuac-container
    image: mongo:latest
    ports:
        - "27017:27017"
    command: --smallfiles

volumes:
  bundle:
    driver: local
